import { ApolloClient, InMemoryCache } from '@apollo/client';
import type { InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import gql from 'graphql-tag';
import { Key, useState } from 'react';

interface Info {
  count: number;
  pages: number;
  next: number;
  prev: number;
}

interface Character {
  id: number;
  name: String;
  status: String;
  species: String;
  image: String;
}
interface Characters {
  info: Info;
  results: [Character];
}

const Home = (props: Characters): JSX.Element => {
  console.log(props);
  const initialState = props.results;
  // const [characters, setCharacters] = useState(characters.results);

  return (
    <div className={styles.container}>
      <Head>
        <title>Rick&MortyDex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>PERSONAGENS</h1>

        {props.results &&
          props.results.map((character) => {
            return <h1 key={character.id}>{character.name}</h1>;
          })}
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://rickandmortyapi.com/graphql/',
    cache: new InMemoryCache(),
  });
  const { data } = await client.query({
    query: gql`
      query {
        characters(page: 1) {
          info {
            count
            pages
            prev
            next
          }
          results {
            id
            name
            status
            image
            species
          }
        }
      }
    `,
  });

  return {
    props: {
      info: data.characters.info,
      results: data.characters.results,
    },
  };
}

export default Home;
